[settings, button] = Tools.settingsdlg(...
    'Description', 'This dialog will set the parameters used by FMINCON()',...
    'title'      , 'FMINCON() options',...
    'separator'  , 'Unconstrained/General',...
    {'This is a checkbox'; 'Check'}, [true true],...
    {'Tolerance X';'TolX'}, 1e-6,...
    {'Tolerance on Function';'TolFun'}, 1e-6,...
    'Algorithm'  , {'active-set','interior-point'},...
    'separator'  , 'Constrained',...
    {'Tolerance on Constraints';'TolCon'}, 1e-6)
