function [outputArg1,outputArg2] = addECGAnn(this)
    if (this.Workspace.EEG.nbchan == 1)
       Tools.plotECG(this.Workspace.EEG.times, this.Workspace.EEG, 'b-',...
                                'ShowInformationList','none',...
                                'ShowAxisTicks','on',...
                                'mmPerSec', 25,...
                                'YLimMode', 'fixed',...
                                'ShowInformationList','none',...
                                'Parent',  this.Figures(end));
    else
               Tools.plotECG(this.Workspace.EEG.times, this.Workspace.EEG, 'b-',...
                                'ShowInformationList','none',...
                                'ShowAxisTicks','on',...
                                'mmPerSec', 25,...
                                'AutoStackSignals', {this.Workspace.EEG.chanlocs.labels},...
                                'YLimMode', 'fixed',...
                                'ShowInformationList','none',...
                                'Parent',  this.Figures(end));
    end
    uAxis = gca;
    
    hold on
    plot(uAxis,this.Workspace.EEG.RTopTime,this.Workspace.EEG.RTopVal,'ro')
    ml = max(ylim);
    nd = (this.Workspace.EEG.RTopVal*0) + ml;
    plot(uAxis,this.Workspace.EEG.RTopTime,nd,'rv','MarkerFaceColor','r')
    
    %% Plot the IBI value labels in between the top r-top markers:
    text( uAxis, double(this.Workspace.EEG.RTopTime(1:end-1) + this.Workspace.EEG.RTopTime(2:end))/2, ...
        double(nd(1:end-1))/1.05,...
        int2str(this.Workspace.EEG.ibis(:)*1000),...
        'FontSize', 8, 'HorizontalAlignment', 'center');
    Child = get(gca, 'Children');
    set(Child, 'Clipping', 'on');
    hold off
end

